export type Person = {
  name: string
  title: string
  email: string
  role: string
}

export const people: Person[] = [
  {
    name: 'Russell Bernier',
    title: 'Direct Group Analyst',
    email: 'Alfonso3@yahoo.com',
    role: 'Member',
  },
  {
    name: 'Henry Bernhard',
    title: 'Product Response Planner',
    email: 'Roger_Padberg97@gmail.com',
    role: 'Member',
  },
  {
    name: 'Winston Huels',
    title: 'Central Intranet Administrator',
    email: 'Angel_Howe18@yahoo.com',
    role: 'Member',
  },
  {
    name: 'Rhonda Willms',
    title: 'Chief Division Architect',
    email: 'Arthur.King33@yahoo.com',
    role: 'Admin',
  },
  {
    name: 'Justin Lebsack',
    title: 'International Security Strategist',
    email: 'Marjorie.Carroll55@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Israel Dach',
    title: 'Principal Security Representative',
    email: 'Austen.Bruen28@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Suzanne Smitham',
    title: 'Internal Mobility Orchestrator',
    email: 'Stevie_Okuneva61@gmail.com',
    role: 'Member',
  },
  {
    name: 'Clay Schmitt',
    title: 'Chief Usability Planner',
    email: 'Calista69@yahoo.com',
    role: 'Member',
  },
  {
    name: 'Gregg Pagac',
    title: 'District Identity Planner',
    email: 'Elise55@yahoo.com',
    role: 'Member',
  },
  {
    name: 'Samuel Gislason',
    title: 'Investor Accounts Liaison',
    email: 'Kayla.Dicki@yahoo.com',
    role: 'Member',
  },
  {
    name: 'Sylvester Towne',
    title: 'Future Communications Technician',
    email: 'Fannie_Pouros14@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Noel Kovacek',
    title: 'Future Communications Officer',
    email: 'Jamal75@gmail.com',
    role: 'Member',
  },
  {
    name: 'Claudia Price',
    title: 'Customer Division Orchestrator',
    email: 'Zion.Stehr71@gmail.com',
    role: 'Member',
  },
  {
    name: 'Kristy Kemmer',
    title: 'Senior Factors Strategist',
    email: 'Jarod4@yahoo.com',
    role: 'Admin',
  },
  {
    name: 'Dewey Walter',
    title: 'Customer Mobility Architect',
    email: 'Mertie41@yahoo.com',
    role: 'Member',
  },
  {
    name: 'Regina Keebler',
    title: 'Human Creative Designer',
    email: 'Theodora12@gmail.com',
    role: 'Member',
  },
  {
    name: 'Ms. Garrett Weber II',
    title: 'Senior Creative Supervisor',
    email: 'Delmer.Stanton@yahoo.com',
    role: 'Member',
  },
  {
    name: 'Byron Yundt',
    title: 'Customer Communications Agent',
    email: 'Sabryna_Kuhn@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Mr. Kristopher Kozey',
    title: 'Regional Research Administrator',
    email: 'Bernhard66@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Mindy Ward',
    title: 'Principal Tactics Technician',
    email: 'Itzel.Fisher41@gmail.com',
    role: 'Admin',
  },
  {
    name: 'Israel Fahey',
    title: 'Chief Web Technician',
    email: 'Mac.Schinner@gmail.com',
    role: 'Member',
  },
  {
    name: 'Devin Rowe',
    title: 'Central Communications Orchestrator',
    email: 'Winfield.Hudson64@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Herman Rohan DVM',
    title: 'Product Optimization Consultant',
    email: 'Rita.Bode12@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Louise Schoen',
    title: 'Principal Creative Representative',
    email: 'Oda27@yahoo.com',
    role: 'Admin',
  },
  {
    name: 'Earnest Davis',
    title: 'Corporate Division Strategist',
    email: 'Casey_Bechtelar73@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Marshall Bashirian',
    title: 'Central Integration Planner',
    email: 'Lonnie_Johnson64@yahoo.com',
    role: 'Member',
  },
  {
    name: 'Dr. Darnell Corkery',
    title: 'Global Markets Supervisor',
    email: 'Meagan_Krajcik@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Eleanor Jacobs',
    title: 'Product Creative Specialist',
    email: 'Coralie.Reynolds74@yahoo.com',
    role: 'Member',
  },
  {
    name: 'Gloria Fahey',
    title: 'Principal Creative Engineer',
    email: 'Ryan.Kris@gmail.com',
    role: 'Member',
  },
  {
    name: 'Toni Hettinger',
    title: 'Dynamic Research Technician',
    email: 'Berniece_Hansen73@gmail.com',
    role: 'Member',
  },
  {
    name: 'Jeff Parisian',
    title: 'Product Applications Technician',
    email: 'Marguerite30@gmail.com',
    role: 'Member',
  },
  {
    name: 'Elena Halvorson',
    title: 'Human Solutions Representative',
    email: 'Kameron53@gmail.com',
    role: 'Member',
  },
  {
    name: 'Pat Wisoky',
    title: 'Customer Accounts Agent',
    email: 'Damon18@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Amber Osinski',
    title: 'Customer Mobility Associate',
    email: 'Reagan76@yahoo.com',
    role: 'Member',
  },
  {
    name: 'Leah Conroy',
    title: 'Regional Usability Planner',
    email: 'Wilfred.Prosacco37@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Linda Spencer',
    title: 'Direct Creative Associate',
    email: 'Chaya.Haag49@gmail.com',
    role: 'Owner',
  },
  {
    name: 'Alonzo Hahn',
    title: 'Internal Data Developer',
    email: 'Timmy31@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Henrietta Lakin',
    title: 'District Markets Orchestrator',
    email: 'Edythe_Volkman@yahoo.com',
    role: 'Admin',
  },
  {
    name: 'Felicia Homenick',
    title: 'Product Data Architect',
    email: 'Elmira18@hotmail.com',
    role: 'Member',
  },
  {
    name: 'April Lemke II',
    title: 'International Brand Supervisor',
    email: 'Afton.Weber@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Van Sawayn',
    title: 'International Group Analyst',
    email: 'Aiyana71@gmail.com',
    role: 'Member',
  },
  {
    name: 'Marcella Witting',
    title: 'Human Web Consultant',
    email: 'Kenton_Olson@gmail.com',
    role: 'Member',
  },
  {
    name: 'Genevieve Fadel',
    title: 'Internal Division Manager',
    email: 'Matilde.Klein45@gmail.com',
    role: 'Member',
  },
  {
    name: 'Darrell Rodriguez',
    title: 'International Tactics Developer',
    email: 'Bonita65@gmail.com',
    role: 'Member',
  },
  {
    name: 'Casey Mitchell',
    title: 'Regional Communications Assistant',
    email: 'Ezekiel79@gmail.com',
    role: 'Member',
  },
  {
    name: 'Felipe Donnelly III',
    title: 'Dynamic Markets Engineer',
    email: 'Adalberto83@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Nichole Stehr',
    title: 'Senior Mobility Supervisor',
    email: 'Sim_Rolfson21@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Boyd Kerluke',
    title: 'Regional Factors Orchestrator',
    email: 'Jamarcus_Swaniawski@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Dora Friesen II',
    title: 'Global Paradigm Associate',
    email: 'Edd36@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Orville Shields',
    title: 'Chief Configuration Coordinator',
    email: 'Jackson.OHara@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Mona Cole',
    title: 'Customer Paradigm Officer',
    email: 'Scottie_Grant@gmail.com',
    role: 'Member',
  },
  {
    name: 'Johnathan Mayer',
    title: 'Investor Communications Coordinator',
    email: 'Cortez_Metz62@yahoo.com',
    role: 'Member',
  },
  {
    name: 'Javier Greenfelder',
    title: 'District Factors Designer',
    email: 'Evelyn.Lesch@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Jason Rodriguez Sr.',
    title: 'Internal Brand Representative',
    email: 'Aidan53@yahoo.com',
    role: 'Member',
  },
  {
    name: 'Camille White',
    title: 'Senior Group Liaison',
    email: 'Gene.Balistreri42@gmail.com',
    role: 'Member',
  },
  {
    name: 'Mr. Dewey Bradtke',
    title: 'Senior Security Representative',
    email: 'Jonas_Jacobs72@gmail.com',
    role: 'Member',
  },
  {
    name: 'Cameron Hodkiewicz',
    title: 'National Mobility Assistant',
    email: 'Leone7@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Clarence Herzog',
    title: 'Customer Quality Architect',
    email: 'Vince77@yahoo.com',
    role: 'Member',
  },
  {
    name: 'Antonia Muller I',
    title: 'Customer Functionality Officer',
    email: 'Noel_Lockman52@gmail.com',
    role: 'Member',
  },
  {
    name: 'Miss Abel Shanahan',
    title: 'Product Division Director',
    email: 'Bianka36@hotmail.com',
    role: 'Admin',
  },
  {
    name: 'Edwin Boehm',
    title: 'Lead Interactions Manager',
    email: 'Leonardo81@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Miss Sheryl Kozey',
    title: 'Regional Creative Liaison',
    email: 'Ericka11@gmail.com',
    role: 'Member',
  },
  {
    name: 'Miss Garry Gerhold',
    title: 'International Mobility Designer',
    email: 'Agustin92@gmail.com',
    role: 'Member',
  },
  {
    name: 'Danny Russel',
    title: 'Investor Metrics Coordinator',
    email: 'Eriberto63@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Kristin Hettinger',
    title: 'Investor Response Associate',
    email: 'Precious.Dicki39@gmail.com',
    role: 'Member',
  },
  {
    name: 'June Walter',
    title: 'Legacy Applications Manager',
    email: 'Keshaun.Hilll@yahoo.com',
    role: 'Member',
  },
  {
    name: 'Gregg Mraz',
    title: 'Corporate Creative Strategist',
    email: 'Darlene.Yost@yahoo.com',
    role: 'Member',
  },
  {
    name: 'Gilbert Donnelly',
    title: 'Customer Data Coordinator',
    email: 'Mariam_Ledner@yahoo.com',
    role: 'Member',
  },
  {
    name: 'Dean Steuber',
    title: 'National Security Facilitator',
    email: 'Winona_Bradtke@gmail.com',
    role: 'Admin',
  },
  {
    name: 'Darrin Gleason IV',
    title: 'Direct Accounts Engineer',
    email: 'Hilda.Kuvalis41@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Pablo Funk',
    title: 'Central Markets Designer',
    email: 'Drake_Ward@yahoo.com',
    role: 'Member',
  },
  {
    name: 'Doyle Bode',
    title: 'Corporate Functionality Representative',
    email: 'Jammie_Wilderman@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Neal Greenholt Sr.',
    title: 'Forward Brand Planner',
    email: 'Braxton_Langosh@yahoo.com',
    role: 'Member',
  },
  {
    name: 'Keith Boehm',
    title: 'Dynamic Mobility Supervisor',
    email: 'Myrtis_Hartmann@yahoo.com',
    role: 'Member',
  },
  {
    name: 'Marion Rolfson',
    title: 'Senior Paradigm Developer',
    email: 'Uriel_Gislason48@gmail.com',
    role: 'Member',
  },
  {
    name: 'Brett Sanford',
    title: 'Internal Paradigm Specialist',
    email: 'Efren83@yahoo.com',
    role: 'Member',
  },
  {
    name: 'Jessie Reilly',
    title: 'Dynamic Integration Facilitator',
    email: 'Tristin.Hodkiewicz@yahoo.com',
    role: 'Member',
  },
  {
    name: 'Beth Kuphal',
    title: 'Global Solutions Engineer',
    email: 'Everett85@yahoo.com',
    role: 'Member',
  },
  {
    name: 'Doreen Jones',
    title: 'Customer Mobility Architect',
    email: 'Bonita16@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Rose Armstrong',
    title: 'Senior Division Orchestrator',
    email: 'Jakob59@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Miss Lester Collier',
    title: 'Corporate Functionality Supervisor',
    email: 'Juvenal38@gmail.com',
    role: 'Member',
  },
  {
    name: 'Scott Jones MD',
    title: 'Senior Optimization Orchestrator',
    email: 'Loraine40@gmail.com',
    role: 'Admin',
  },
  {
    name: 'Hattie Thiel',
    title: 'Dynamic Factors Associate',
    email: 'Rogelio_Hodkiewicz39@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Juanita Borer',
    title: 'Dynamic Accounts Liaison',
    email: 'Stuart.Maggio@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Amos Murphy I',
    title: 'Direct Factors Specialist',
    email: 'Garrett_Romaguera58@gmail.com',
    role: 'Member',
  },
  {
    name: 'Allan Bode',
    title: 'Future Metrics Supervisor',
    email: 'Berneice_Bartoletti1@gmail.com',
    role: 'Member',
  },
  {
    name: 'Dr. Beulah Fisher',
    title: 'Corporate Creative Strategist',
    email: 'Mavis63@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Pam Turner DVM',
    title: 'International Program Supervisor',
    email: 'Colton.Turner45@gmail.com',
    role: 'Member',
  },
  {
    name: 'Wendell Lowe',
    title: 'Chief Creative Strategist',
    email: 'Nellie_Connelly@gmail.com',
    role: 'Member',
  },
  {
    name: 'Mrs. Bertha Sanford',
    title: 'Future Functionality Producer',
    email: 'Lacey90@yahoo.com',
    role: 'Member',
  },
  {
    name: 'Nancy Howe',
    title: 'Central Directives Designer',
    email: 'Maverick.Willms9@yahoo.com',
    role: 'Member',
  },
  {
    name: 'Luis Schamberger',
    title: 'National Marketing Designer',
    email: 'Geoffrey_Pagac@hotmail.com',
    role: 'Member',
  },
  {
    name: 'Lewis Gaylord',
    title: 'Principal Brand Coordinator',
    email: 'Marlee.Fahey65@gmail.com',
    role: 'Member',
  },
  {
    name: 'Nicolas Schneider',
    title: 'Customer Implementation Planner',
    email: 'Ferne.Jakubowski27@gmail.com',
    role: 'Member',
  },
  {
    name: 'Tara Deckow',
    title: 'Chief Creative Architect',
    email: 'Tony.Gutkowski55@gmail.com',
    role: 'Member',
  },
  {
    name: 'Everett Leffler',
    title: 'Dynamic Integration Director',
    email: 'Justina_Mosciski@gmail.com',
    role: 'Member',
  },
]

export const getPeople = (searchQuery: string, page: number) => {
  const startIndex = (page - 1) * 10
  const endIndex = startIndex + 10
  const filteredPeople = people.filter((person) =>
    person.name.toLowerCase().includes(searchQuery?.toLowerCase())
  )
  return { people: filteredPeople.slice(startIndex, endIndex), totalResults: filteredPeople.length }
}
